In [1]:
print("Hello Python")

Hello Python

In [2]:
## Data types
## Variables

In [3]:
## Operator's in python

In [4]:
# Arithmetic Operator

In [5]:
# + 
# -
# *
# /
# %
# **

In [11]:
## add 2 and 3 
print( 2 + 3)
print( 6 - 4)
print( 2 * 4)
print( 6 / 3)
print( 10 % 2)
print( 3 ** 2)

5
2
8
2.0
0
9

# List in Python

In [2]:
## Create Empty list

x = []
print(x)
print(type(x))

[]
<class 'list'>

In [ ]:
# Create a list as marks and store students marks
# Can we store the int values

In [4]:
marks = [99, 98, 95, 96]
print(marks)
print(type(marks))

[99, 98, 95, 96]
<class 'list'>

In [5]:
## string valyes
name = ["Rohan", "Mohan", "Riya", "Priya"]
print(name)
print(type(name))

['Rohan', 'Mohan', 'Riya', 'Priya']
<class 'list'>

In [6]:
# decimal values

price = [80.5, 90.6, 70.4]
print(price)
print(type(price))

[80.5, 90.6, 70.4]
<class 'list'>

In [8]:
## boolean values
x = [True, False]
print(x, type(x))

[True, False] <class 'list'>

In [10]:
# Mixed  data type
student = ["Alice", 30, "MBA", 7000, True, 98.5]
print(student, type(student))

['Alice', 30, 'MBA', 7000, True, 98.5] <class 'list'>

In [11]:
# Check for the duplicates 

Employees = ['Mohan', 'Rohan', 'Sohan', 'Mohan', 'Rohan']
print(Employees)

['Mohan', 'Rohan', 'Sohan', 'Mohan', 'Rohan']

In [ ]:
# Indexing in list

In [17]:
Students = ['Alice', 'Bob', 'Rohan', 'David', 'Riya']
print(Students)

## acces the first elemnet of list
print(Students[0])

### acces the third elemnet of list 
print(Students[2])

# ## acces the fourth elemnet of list
print(Students[3])

['Alice', 'Bob', 'Rohan', 'David', 'Riya']
Alice
Rohan
David

In [ ]:
# Negative indexing

In [18]:
print(Students[-1])

Riya

In [19]:
print(Students[-2])

David

In [21]:
print(Students[-3])

Rohan

# Slicing

In [ ]:
[Start:stop:step]

In [3]:
Students = ['Alice', 'Bob', 'Rohan', 'David', 'Riya']
print(Students)

['Alice', 'Bob', 'Rohan', 'David', 'Riya']

In [20]:
# access th elment from 0 to 3
print(Students[:4])

['Alice', 'Bob', 'Rohan', 'David']

In [5]:
# acess the empemnt from 0 to 2
print(Students[0:3])

['Alice', 'Bob', 'Rohan']

In [6]:
# acces the emelent 1 to 4
print(Students[1:4])

['Bob', 'Rohan', 'David']

In [7]:
print(Students[2:6])

['Rohan', 'David', 'Riya']

In [9]:
## acces the alternate elemnet from the list

print(Students[::2])

['Alice', 'Rohan', 'Riya']

In [10]:
print(Students[1::2])

['Bob', 'David']

In [12]:
print(Students[::3])

['Alice', 'David']

In [13]:
## Reverse the list
print(Students[::-1])

['Riya', 'David', 'Rohan', 'Bob', 'Alice']

In [15]:
print(Students[2::])

['Rohan', 'David', 'Riya']

In [17]:
print(Students[1::])

['Bob', 'Rohan', 'David', 'Riya']

In [1]:
# List Methods
#append()

In [7]:
std = ['Rohan', 'Riya' ,'Sohan']
print(std)

['Rohan', 'Riya', 'Sohan']

In [8]:
# add Mohan in std list
std.append('Mohan')
print(std)

['Rohan', 'Riya', 'Sohan', 'Mohan']

In [9]:
# add age 34
std.append(34)
print(std)

['Rohan', 'Riya', 'Sohan', 'Mohan', 34]

In [10]:
# 2: insert()
# add Priya at 1 indexing in std list
std.insert(1, 'Priya')
print(std)

['Rohan', 'Priya', 'Riya', 'Sohan', 'Mohan', 34]

In [11]:
# 3: extend()
#Adds multiple elements from another list

In [12]:
list1 = [1,2,3]
list2 = [4,5,6]

list1.extend(list2)
print(list1)

[1, 2, 3, 4, 5, 6]

In [15]:
#4: remove()
#Remove a specific element

In [16]:
numbers = [1,2,3,4]
numbers.remove(3)
print(numbers)

[1, 2, 4]

In [17]:
# 5 : pop()
#Removes an element using index

In [19]:
numbers = [1,2,3,4]
print(numbers)

# remove the first index element
numbers.pop(1)
print(numbers)

[1, 2, 3, 4]
[1, 3, 4]

In [21]:
# clear()
#Removes all element from the list

In [23]:
numbers = [1,2,3,4]
print(numbers)
numbers.clear()
print(numbers)

[1, 2, 3, 4]
[]

In [24]:
# 7: index()
#Returns the index position of a value
numbers = [10,20,30]
print(numbers.index(20))

1

In [ ]:
# 8 : count()
counts how many times a value appears

In [29]:
emp_name = ['Alice', 'Bob', 'David', 'Rohan', 'Alice', 'Bob']
print(emp_name)

print(emp_name.count('Alice'))
print(emp_name.count('Bob'))
print(emp_name.count('David'))

['Alice', 'Bob', 'David', 'Rohan', 'Alice', 'Bob']
2
2
1

In [ ]:
# sort()
sorts the list in order
# asc
# desc

In [41]:
salary = [75000, 65000, 78000, 45000, 66000]
print(salary)
# sort salary in asc orders
salary.sort()
print("Asc:", salary)

[75000, 65000, 78000, 45000, 66000]
Asc: [45000, 65000, 66000, 75000, 78000]

In [45]:
salary = [75000, 65000, 78000, 45000, 66000]
print(salary)
salary.sort(reverse = True)
print("Desc:", salary)

[75000, 65000, 78000, 45000, 66000]
Desc: [78000, 75000, 66000, 65000, 45000]

In [48]:
# 10 : reverse()
#Reverses the list order.
salary = [75000, 65000, 78000, 45000, 66000]
print(salary)

salary.reverse()
print(salary)

[75000, 65000, 78000, 45000, 66000]
[66000, 45000, 78000, 65000, 75000]

In [50]:
# 11 : copy()
# Creates a copy of this list
list1 = [10,20,30]
list2 = list1.copy()
print(list1)
print(list2)

[10, 20, 30]
[10, 20, 30]

In [52]:
# len()
salary = [75000, 65000, 78000, 45000, 66000]
print(salary)
print(len(salary))

[75000, 65000, 78000, 45000, 66000]
5

In [54]:
name = ['mohan','rohan', 'riya']
print(name)
print("Total Elemenets :", len(name))

['mohan', 'rohan', 'riya']
3

In [56]:
# max()
salary = [75000, 65000, 78000, 45000, 66000]
print(max(salary))

78000

In [57]:
# min()
salary = [75000, 65000, 78000, 45000, 66000]
print(min(salary))

45000

In [58]:
# sum()
salary = [75000, 65000, 78000, 45000, 66000]
print(sum(salary))

329000

In [60]:
# del 
numbers = [10,20,30]
print(numbers)

del numbers[1]
print(numbers)

[10, 20, 30]
[10, 30]

In [1]:
# Tuples in python
()

()

In [2]:
# CREATE a tuple
# Create a empty tuple

In [4]:
x = ()
print(x)
print(type(x))

()
<class 'tuple'>

In [5]:
# create a tuple and store string values
x = ('Alice', 'Bob', 'David')
print(x)

('Alice', 'Bob', 'David')

In [6]:
y = (200, 400, 500, 600)
print(y, type(y))

(200, 400, 500, 600) <class 'tuple'>

In [7]:
price = (40.5, 70.5, 40.6, 70.8)
print(price)

(40.5, 70.5, 40.6, 70.8)

In [8]:
case = (True, False)
print(case)

(True, False)

In [36]:
x1 = (10, 20, 10, 20, 30)
print(x1)

(10, 20, 10, 20, 30)

In [16]:
std = ('Alice', 30, 'MCA', 80)
print(std)

('Alice', 30, 'MCA', 80)

In [9]:
## Accesssing Element in tuple(INdexing)

In [13]:
name = ('Alice', 'Bob', 'David')
print(name[0])
print(name[1])
print(name[-1])

Alice
Bob
David

In [14]:
# Slicing in tuple(start :stop:step)

In [24]:
students = ('Alice', 'Bob', 'David', 'Riya', 'Mohan')
print(students)
# acess the name 0 to 3
print(students[:4])

print(students[1:4])
print(studnets[2::])

print(studnets[::2])

('Alice', 'Bob', 'David', 'Riya', 'Mohan')
('Alice', 'Bob', 'David', 'Riya')
('Bob', 'David', 'Riya')
('David', 'Riya', 'Mohan')
('Alice', 'David', 'Mohan')

In [25]:
print(studnets[::3])

('Alice', 'Riya')

In [27]:
print(students[::-1])

('Mohan', 'Riya', 'David', 'Bob', 'Alice')

In [28]:
# Function in tuple

In [29]:
# len ()

In [31]:
t = (10, 20, 30, 40)
print(t, type(t))
print(len(t))

(10, 20, 30, 40) <class 'tuple'>
4

In [32]:
# max()

In [33]:
t = (10, 20, 30, 40)
print(max(t))

40

In [34]:
# min()
t = (10, 20, 30, 40)
print(min(t))

10

In [35]:
# sum()
t = (10, 20, 30, 40)
print(sum(t))

100

In [38]:
# count()
t = (10, 20, 30, 40, 40, 20)
print(t.count(20))
print(len(t))

2
6

In [ ]:
# index()

In [40]:
t = (10, 20, 30, 40)
print(t.index(30))

2

In [41]:
# set in python
Set in Python
A set is a collection of unique items in Python. 
Sets do not allow duplicate items and do not maintain any particular order so it can’t be indexed.

In [45]:
# Create a empty set
set1 = {}
print(set1)
print(type(set1))

{}
<class 'dict'>

In [47]:
# set()

x = set()
print(x, type(x))

set() <class 'set'>

In [48]:
x = {"A", "B", "C"}
print(x)

{'C', 'B', 'A'}

In [49]:
x1 = {1,2,3,4}
print(x1)

{1, 2, 3, 4}

In [56]:
y1 = {10.5, 15.6, 20.7}
print(y1)

{10.5, 20.7, 15.6}

In [57]:
x2 = {True, False}
print(x2)

{False, True}

In [55]:
x2 = {False, True}
print(x2)

{False, True}

In [58]:
x3 = {10, 20, 10, 20}
print(x3)

{10, 20}

In [60]:
num = {200, 300, 150, 500}
print(num)

{200, 300, 500, 150}

In [62]:
# add()
num = {200, 300, 150, 500}
num.add(450)
print(num)

{450, 200, 300, 500, 150}

In [65]:
# remove()
num = {200, 300, 150, 500}
num.remove(300)
print(num)

{200, 500, 150}

In [69]:
# discard()
num = {200, 300, 150, 500}
num.discard(600)
print(num)

{200, 300, 500, 150}

In [71]:
# clear()

num = {200, 300, 150, 500}
num.clear()
print(num)

set()

In [2]:
# update()
num1 = {1,2,3}
num1.update([4,5,6])
print(num1)

{1, 2, 3, 4, 5, 6}

In [78]:
# set operations
# union
num1 = {1,2,3,4}
num2 = {7,8,4}
print(num1.union(num2))

{1, 2, 3, 4, 7, 8}

In [75]:
# intersection
num1 = {1,2,3,4}
num2 = {7,8, 3, 4}
print(num1.intersection(num2))

{3, 4}

In [77]:
# Difference
num1 = {1,2,3,4}
num2 = {7,8, 3, 4}
print(num1.difference(num2))
print(num2.difference(num1))

{1, 2}
{8, 7}

In [1]:
# Dictionary  in python

In [3]:
#Create a students dictionary
std = [101,'Amit', 'BCA', 102, 'BOB','MCA']

In [4]:
{}

{}

In [7]:
std = {"Id": [1,2,3,4,5], "Name" : ["Rohan", "Mohan", "Riya", "Priya"]}
print(std)

{'Id': [1, 2, 3, 4, 5], 'Name': ['Rohan', 'Mohan', 'Riya', 'Priya']}

In [5]:
emp = {"emp_id" : [101,102,103], "emp_name" : ["Alice", "Bob", "David"]}
print(emp)

{'emp_id': [101, 102, 103], 'emp_name': ['Alice', 'Bob', 'David']}

In [9]:
# indexing

In [11]:
# Returns the only id from emp dict
print(emp["emp_id"])

[101, 102, 103]

In [12]:
# emp_name
print(emp["emp_name"])

['Alice', 'Bob', 'David']

In [13]:
print(emp["emp_id"][1])

102

In [14]:
print(emp["emp_id"][2])

103

In [15]:
print(emp["emp_id"][:3])

[101, 102, 103]

In [16]:
print(emp["emp_id"][1:3])

[102, 103]

In [17]:
print(emp["emp_id"][-1])

103

In [19]:
print("Id:" , emp["emp_id"][0], "Name:", emp["emp_name"][0])

Id: 101 Name: Alice

In [22]:
print("Id:", emp["emp_id"][1:3], "Name:", emp["emp_name"][1:3])

Id: [102, 103] Name: ['Bob', 'David']

In [23]:
print("Id:", emp["emp_id"][::], "Name:", emp["emp_name"][1:3])

Id: [101, 102, 103] Name: ['Bob', 'David']

In [24]:
# Methods

In [ ]:
# keys()

In [25]:
emp = {"emp_id" : [101,102,103], "emp_name" : ["Alice", "Bob", "David"]}
print(emp)

{'emp_id': [101, 102, 103], 'emp_name': ['Alice', 'Bob', 'David']}

In [27]:
print(emp.keys())

dict_keys(['emp_id', 'emp_name'])

In [28]:
# values()

In [29]:
emp.values()

dict_values([[101, 102, 103], ['Alice', 'Bob', 'David']])

In [30]:
# items()

In [31]:
emp.items()

dict_items([('emp_id', [101, 102, 103]), ('emp_name', ['Alice', 'Bob', 'David'])])

In [ ]:
# update

In [6]:
emp.update({"dept_name" :["Hr", "It", "sales", "Marketing"]})

In [7]:
emp

{'emp_id': [101, 102, 103],
 'emp_name': ['Alice', 'Bob', 'David'],
 'dept_name': ['Hr', 'It', 'sales', 'Marketing']}

In [36]:
# get()

In [37]:
print(emp.get("dept_name"))

['Hr', 'It', 'sales', 'Marketing']

In [42]:
# pop()

In [39]:
emp

{'emp_id': [101, 102, 103],
 'emp_name': ['Alice', 'Bob', 'David'],
 'dept_name': ['Hr', 'It', 'sales', 'Marketing']}

In [40]:
emp.pop("emp_name")

['Alice', 'Bob', 'David']

In [41]:
emp

{'emp_id': [101, 102, 103], 'dept_name': ['Hr', 'It', 'sales', 'Marketing']}

In [43]:
# popitem()

In [8]:
emp

{'emp_id': [101, 102, 103],
 'emp_name': ['Alice', 'Bob', 'David'],
 'dept_name': ['Hr', 'It', 'sales', 'Marketing']}

In [10]:
emp.popitem()

('dept_name', ['Hr', 'It', 'sales', 'Marketing'])

In [46]:
emp

{'emp_id': [101, 102, 103]}

In [47]:
# remove()

In [13]:
print(emp["emp_id"].remove(102))

None

In [15]:
emp

{'emp_id': [101, 103], 'emp_name': ['Alice', 'Bob', 'David']}

In [50]:
# copy()

In [51]:
emp = {"emp_id" : [101,102,103], "emp_name" : ["Alice", "Bob", "David"]}
print(emp)

{'emp_id': [101, 102, 103], 'emp_name': ['Alice', 'Bob', 'David']}

In [52]:
emp1 = emp.copy()
print(emp1)

{'emp_id': [101, 102, 103], 'emp_name': ['Alice', 'Bob', 'David']}

In [53]:
#  clear()

In [54]:
emp.clear()

In [55]:
emp

{}

In [56]:
std = {"Name" : "Mohan", "Id" : 105}
print(std)

{'Name': 'Mohan', 'Id': 105}

In [57]:
std["Name"] = "Rohan"

In [58]:
std

{'Name': 'Rohan', 'Id': 105}

# Conditional Statementns

In [60]:
# If only with True

In [61]:
price = 900
print(price)

900

In [63]:
price = 1900
if price > 1000:
    print("High Price")

High Price

In [64]:
marks = 95
if marks > 90:
    print("Pass")

Pass

In [69]:
name = "Mohan"
if name == "Rohan":
    print("Hello", "Rohan!")

In [70]:
# if else

In [71]:
price = 900
if price > 1000:
    print("High Price")
else:
    print("Low Price")

Low Price

In [72]:
username = "Mohan@123"
if username == "Mohan@123":
    print("Login")

else:
    print("Not login")

Login

In [2]:
x = 10
if x >  5:
    print("X is greater than 5")
else:
    print("X is not greater than 5")

X is greater than 5

In [4]:
# Check Even and odd
num = 9
if num % 2 == 0:
    print("it's Even number")
else :
    print("It's Odd Number")

It's Odd Number

In [5]:
# 
marks = 85
if marks >= 90:
    print("A Grade")
else:
    print("B Grade")

B Grade

In [6]:
# if- elif-else

In [8]:
price = 100
if price >= 120:
    print("High Price")
elif price >= 70:
    print("Avg Price")
else:
    print("Low Price")

Avg Price

In [9]:
# Number Comparision

In [ ]:
num = 0
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

In [10]:
score = 90
if score > 100:
    print("A grade")
elif score > 90:
    print("B grade")
elif  score > 80:
    print("C garde")
else :
    print("D grade")

C garde

In [11]:
# Check the Largest Three Numbers

In [13]:
a = 10
b = 20
c = 15
if a > b and a > c:
    print("a is largest")
elif b > a and b > c:
    print("b is largest")
else:
    print("c is largest")

b is largest

In [14]:
# Age Category

In [15]:
age = 45
if  age < 13:
    print("child")
elif age < 20:
    print("Teenager")
elif age < 60:
    print("Adult")
else:
    print("Senior citizen")

Adult

In [16]:
# Login System

In [17]:
username = "admin"
password = "1234"
if username == "admin" and password == "1234":
    print("Login succesful")
elif username !=  "admin":
    print("Wrong username")
else:
    print("Wrong Password")

Login succesful

In [18]:
temp = 40
if temp > 40:
    print("Very Hot")
elif temp > 25:
    print("Warm")
else :
    print("cold")

Warm

In [ ]:
# Nested if else
if :
if
    else


else

In [ ]:
# Check Positive Even and Odd

In [22]:
num = -1
if num > 0:
    if num % 2 == 0:
        print("Positive Even")
    else:
        print("Positive odd")
else:
    print("Negative Number")

Negative Number

In [34]:
num = 0
if num > 0:
    if num > 50:
        print("Number is between 1 and 50")
    elif num > 30:
        print("Number is between 1 to 40")
       
    else:
        print("Number is greater than 50")

elif num == 0:
    print("Number is Zero")
else:
    print("Negative Number")

Number is Zero

In [ ]:
# input()

In [17]:
num1 = int(input("Enter a num1 value"))
num2 = int(input("Enter a num2 value"))

if num1 > num2:
    print("Num1 is greater than Num2")
else:
    
    print("Num1 is not greater than Num2")

Enter a num1 value 2
Enter a num2 value 3

Num1 is not greater than Num2

In [39]:
username = input("Enter Your username")
password = input("Enter Your password")
if username == "admin":
    if password == "1234":
        print("Login successfully")
    else:
        print("Not able to Login")

else :
    print("Username is incorrect")

Enter Your username admin
Enter Your password 1234

Login successfully

## 🔹 What is a Function in Python?

In [ ]:
🔹 What is a Function in Python?
A function in Python is a block of reusable code that performs a specific task when called. It helps you organize code, avoid repetition, and improve readability and modularity.

In [ ]:
Types of Functions
1.	Built-in Functions – Already available in Python (e.g., print (), len(), type())
2.	User-defined Functions – Created by the user using the def keyword
________________________________________

In [1]:
# Syntax

In [ ]:
def function_name():


function_name()

In [7]:
# Function with no parameters
def greet():
    print("Happy B'day")


greet()
greet()
greet()

Happy B'day
Happy B'day
Happy B'day

In [19]:
# Function with Parameters
## add two numbers
def add(a,b):
    c = a + b
    print(c)

add(3,4)
add(6,7)
add(10,20)
add(1,1)

7
13
30
2

In [16]:
def add(a=4, b=2):
    c = a + b
    print(c)

add()

6

In [17]:
def add(a,b,c=3):
    z = a + b +c
    print(z)

add(4,5)

12

In [21]:
def fun():
    a = 2
    b = 3
    c = a + b
    d = b - a
    e = a * b
    print("Add:", c ,"Sub:",d, "Mul:", e)
    
fun()

Add: 5 Sub: 1 Mul: 6

In [29]:
def sum(x1,x2):
    x3 = x1 + x2
    x4 = x1 - x2
    x5 = x1 * x2
    print(x3,x4,x5)

sum(9,5)

14 4 45

In [33]:
def product(price):
    if price > 800:
        print("High Price")
    else:
        print("Low Price")

product(1000)
product(600)
product(1500)

High Price
Low Price
High Price

In [34]:
product1 = 1000
if product1 > 800:
    print("High")
else:
    print("Low")

High

In [39]:
def x():
    a1 = int(input("Enter a first value"))
    a2 = int(input("Enter a second value"))
    c = a1 + a2
    print(c)

x()
x()
x()

Enter a first value 1
Enter a second value 1

2

Enter a first value 2
Enter a second value 3

5

Enter a first value 4
Enter a second value 4

8

In [40]:
# Evenn odd

In [43]:
def check_even(num):
    if num % 2 == 0:
        print("Even Number")
    else :
        print("Odd Number")
check_even(1)
check_even(2)

Odd Number
Even Number

In [46]:
def check_result(marks):
    if marks >= 60:
        print("Pass")

    else:
        print("Fail")

check_result(70)
check_result(80)  
check_result(50)

Pass
Pass
Fail

In [49]:
def greet(name, company_name):
    print(f" Hi My name is {name} and i am working in {company_name}")

greet("Rohan", "EY")
greet("Riya", "KPMG")

 Hi My name is Rohan and i am working in EY
 Hi My name is Riya and i am working in KPMG

In [53]:
# Check positive, negative , zero


def check_number(num):
    if num > 0:
        print("Positive")
    elif num < 0:
        print("Negative")
    else :
        print("Zero")
        
check_number(0)  
check_number(5)
check_number(-1)

Zero
Positive
Negative

In [58]:
# return

def add(a,b):
    return  a + b
    
print(add(1,2))
print(add(4,5))

3
9

In [59]:
def add(x,y):
    return x + y

result = add(4,5)
print(result)

9

In [62]:
def is_adult(age):
    if age >= 18:
        return True
    else:
        return False

print(is_adult(20))
print(is_adult(15))

True
False

In [76]:
# Return string
def greet(name):
    return "Hello" + " " + name  +  " " + "from" + " " + "Delhi"

print(greet("Neha"))
print(greet("Riya"))

Hello Neha from Delhi
Hello Riya from Delhi

# string Function in Python

In [2]:
# 1: lower()

In [3]:
text = "HELLO"
print(text.lower())

hello

In [4]:
# 2: upper()

In [5]:
name = 'radha'
print(name.upper())

RADHA

In [6]:
# 3 : title()

In [7]:
name = "radha rai"
print(name.title())

Radha Rai

In [8]:
 # 4: strip()

In [9]:
name = "   hello  "
print(name.strip())

hello

In [10]:
# 5: replace()

In [16]:
text = 'I love python'
print(text.replace('python', 'sql'))

I love sql

In [ ]:
# 6 :  find()

In [17]:
name = 'Mohan'
print(name.find("h"))

2

In [18]:
# 7: count()

In [19]:
text = 'hello'
print(text.count('l'))

2

In [20]:
# 8 : split()

In [23]:
text = "apple, banana, mango, mango"
print(text.split(", "))

['apple', 'banana', 'mango', 'mango']

In [24]:
## 9 :  join() - join list into string

In [25]:
words = ['hello', 'world'] # hello world
print(" ".join(words))

hello world

In [27]:
## 10 : startswith () / endswith()

In [30]:
text = "hello"
print(text.startswith("h"))
print(text.startswith("n"))

True
False

In [31]:
# 11 : endswith

In [33]:
text = "hello"
print(text.endswith("h"))
print(text.endswith("o"))

False
True

In [34]:
## 12 :swapcase()- change upper-lower

In [35]:
text = "Hello World"
print(text.swapcase())

hELLO wORLD

In [36]:
## 13: isalpha() - only letters?

In [39]:
text = "Hello"
print(text.isalpha())

True

In [40]:
## 14 : isdigit() ony numbers?

In [42]:
text = "1234"
print(text.isdigit())

True

In [43]:
# 15 isalnum() letters + Numbers

In [44]:
id = "ram123"
print(id.isalnum())

True

# Loop in python

###  Types of loops in pytohn

In [ ]:
# 1: for loop
# 2: while loop
# 3:Nested loop

In [45]:
# What is for loop ?
Used when you know how many times you want to repeat something.

In [46]:
# print number till 5 using for loop
for i in range(5):
    print(i)

0
1
2
3
4

In [47]:
# Print number 1 to 5 
for i in range(1,6):
    print(i)

1
2
3
4
5

In [49]:
# print number 2 to 20
for i in range(2, 21):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

In [52]:
# print table of 2
for i in range(2, 21, 2):
    print(i)

2
4
6
8
10
12
14
16
18
20

In [53]:
# print even number
for i in range(2,11,2):
    print(i)

2
4
6
8
10

In [54]:
## print elemwnts of list
fruits = ["apple", "banana", "mango"]
for fruit in fruits:
    print(fruit)

apple
banana
mango

In [56]:
marks = [80,76,98,67]
for score in marks:
    print(score)

80
76
98
67

In [58]:
name = "Rohan"
for ch in name:
    print(ch)

R
o
h
a
n

In [59]:
# range(start, stop, step)-

In [60]:
# print alternate  number in between 1 to 20

In [63]:
for i in range(1, 21, 3):
    print(i)

1
4
7
10
13
16
19

In [1]:
## While Loop

In [3]:
name = "sanjana"
for i in name:
    print(i)

s
a
n
j
a
n
a

In [5]:
## syntax of while loop
#while condition:

In [1]:
i = 1
while i < 6:
    print(i)
    i += 1

1
2
3
4
5

In [ ]:
i = 1
while i < 6:
    print(i)
    i += 1

In [4]:
## print    1 to 10
num = 1
while num < 11:
    print(num)
    num += 1

1
2
3
4
5
6
7
8
9
10

In [7]:
## counting from 1 to 5
x = 1
while x<= 5:
    print(x)
    x += 1

1
2
3
4
5

In [8]:
#3 print even numbers up to 10
i = 2
while i <= 10:
    print(i)
    i += 2

2
4
6
8
10

In [12]:
## summing number until 5
i = 2
total = 0
while i <= 10:
    total += 1
    i += 1
print("Sum:", total)

Sum: 9

In [13]:
## pass
## break
## pass

In [15]:
## countdown  from 5
i = 5
while i >= 0:
    print(i)
    i -= 1

5
4
3
2
1
0

In [16]:
## countdown  from 10
num = 10
while num > 0:
    print(num)
    num -= 1

10
9
8
7
6
5
4
3
2
1

In [17]:
##from 1 to 10
num = 1
while num <= 10:
    print(num)
    num += 1

1
2
3
4
5
6
7
8
9
10

In [21]:
## pass
for i in range(5):
    pass

In [23]:


## break

for i in range(5):
    if i == 3:
        break
    print(i)

0
1
2

In [24]:
for i in range(1, 8):
    if i == 6:
        break
    print(i)

1
2
3
4
5

In [25]:
for num in range(1,12, 2):
    if num == 8:
        break
    print(num)

1
3
5
7
9
11

In [29]:
## continue
for i in range(7): 
    if i == 3:
        continue
    print(i)

0
1
2
4
5
6

In [27]:
for i in range(1, 10):
    if i == 7:
        continue
    print(i)

1
2
3
4
5
6
8
9

In [ ]:
Nested Loops in Python Loop inside another loop is nested loop. This means that

In [ ]:
## for j in range():
for i in range():
    print(i)

In [43]:
## print number 1 to 3 for 2 times

for j in range(4):
    for i in range(1,6):
        print(i)
    print("----")

1
2
3
4
5
----
1
2
3
4
5
----
1
2
3
4
5
----
1
2
3
4
5
----

## OOP'S IN Python

In [ ]:
## What is OOP'S ?
OOP is a Programming approach where we can create objects(real-world things) using classes.
## Example A car is a class , and BMW , Audi are objects
## Example2 Studnets is class , Riya, priya, Mohan are objects of class

In [ ]:
##  Feature's of OOP in python
## 1: Code Resuabillity
## 2 : Flexbility
## 3: Data Security

In [ ]:
## class
## Object
#3 Encapsulation
## Inheritance
## Polymorphism
## Abstractions

In [1]:
class class_name:
    pass

In [ ]:
## 1 : Car
## cLass - Car
## Object - BMW, AUDI
## Features - color, speed
## Action - drive()

In [5]:
class Studnets:
    pass

In [4]:
class Employees:
    pass

In [ ]:
class Students: ## class 

std1 = Students()  ## object1
std2 = Students() ## object2
std3 = Students()  ## obejct3

In [13]:
class Students:
    name = "Rohan"
    course = "DA"

std1 = Students()
std2 = Students()
print(std1.name)
print(std1.course)
print(std2.name)

Rohan
DA
Rohan

In [21]:
class Students:   ## class 
    def __init__(self, name, marks, city):   ## Method
        self.name  = name  ## Attributes 
        self.marks = marks ## Attributes 
        self.city = city

 
std1 = Students('Alice', 80, 'Noida') ## obejt1
std2 = Students('Bob', 99, 'Delhi') ## oebject2


## Print the first std name
print(std1.name)


## ## Print the  std name
print(std2.name)


## check the score of std1
print("Name:", std1.name,"Marks:", std1.marks)

Alice
Bob
Name: Alice Marks: 80

In [36]:
class Employees:  ## class
    def __init__(self, emp_id, emp_name, salary):  ## Method1
        self.emp_id =  emp_id
        self.emp_name = emp_name
        self.salary = salary


    def emp_details(self):   ## method2 
        print(f"  Hi my id is {self.emp_id}, name is {self.emp_name}, and my salary is {self.salary}")
        

 
emp1 = Employees(101, 'Alice',89990 )
emp2 = Employees(102, 'Bob', 90000)
emp3 = Employees(103, 'David', 8675636)



print(emp2.salary)
print(emp3.salary)


emp1.emp_details()

90000
8675636
  Hi my id is 101, name is Alice, and my salary is 89990

In [41]:
class Bank:
    def __init__(self, bank_name, balance):
        self.bank_name = bank_name
        self.balance = balance



    def bank_details(self):
        print(f" My bank name is {self.bank_name} and my current balance is {self.balance}")
        


customer1 = Bank("HDFC", 7800000)
customer2 = Bank("ICIC", 9890769)
print(customer1.bank_name)
print(customer2.bank_name)

print(customer1.balance)


## Check all bank details of custpmer1
customer1.bank_details()


## Check all bank details of custpmer1
customer2.bank_details()

HDFC
ICIC
7800000
 My bank name is HDFC and my current balance is 7800000
 My bank name is ICIC and my current balance is 9890769

## 2: Abstraction in oop

In [ ]:
Abstraction in Python: Hiding unnecessary details
Abstraction hides implementation details and shows only the relevant functionality to the user.
Example

In [14]:
class Students:
    def __init__(self, name, course, percentage):
        self.name = name
        self.course = course
        self.percentage = percentage


    def honors(self):
        return self.percentage > 90


std1 = Students("Alice", "MCA", 88)
std2 = Students("Bob", "MBA", 95)


print(std1.percentage)
std1.honors()
print(std2.percentage)

std1.honors()
std2.honors()

88
95

True

In [22]:
class Students:
    def __init__(self,  name, course, marks):
        self.name = name
        self.course = course
        self.marks = marks


    def std_Details(self):
        print(f" My name is {self.name} , i'm pursuing {self.course} and my last sem marks is {self.marks + 2}%")
        



std1 = Students("Alice", "BCA", 89)
std2 = Students("Bob", "MBA", 87)
print(std1.name)

std3 = Students("David", "BBA", 80)


std1.std_Details()
std3.std_Details()

Alice
 My name is Alice , i'm pursuing BCA and my last sem marks is 91%
 My name is David , i'm pursuing BBA and my last sem marks is 82%

##  3 : Encapsulation in python

In [ ]:
Encapsulation in Python: Restricting direct access to attributes & methods
Encapsulation restricts access to certain attributes or methods to protect the data and enforce controlled access.

In [29]:
class Employees:
    def __init__(self, emp_id, emp_name, salary):
        self.emp_id = emp_id
        self.emp_name = emp_name
        self.__salary = salary ## private


    def get_salary(self):  ## Mehod2
        return self.__salary 

emp1 = Employees(101, "Ram", 89000)
emp2 = Employees(102, "Mohan", 87900)
#print(emp1.salary)

print(emp1.get_salary())

89000

In [33]:
## Bank Account
class Bankaccount:
    def __init__(self):
        self.__balance = 0

    def deposit(self, amount):
        self.__balance += amount

    def get_balance(self):
        return self.__balance
        



acc = Bankaccount()
acc.deposit(5000)
print(acc.get_balance())

5000

In [ ]:
Inheritance in Python: Reusing Parent’s prop & methods
Inheritance (parent-child), allows one class (child) to reuse the properties and

In [38]:
class Students: ## class
    def __init__(self, id, name , score): ## Method1
        self.id = id
        self.name = name
        self.score = score

std1 = Students(201, "Amit", 78)
std2 = Studnets(204, "Rohan", 89)## object1
print(std1.name)

class Graduate_students(Students):
    def __init__(self,  name, score, course, City)
        super().__init__( name, score)
        self.course = course
        self.city=  city
        
        
grad_std1 = Graduate_students("Alice", 78, "BCA")
grad_std2 = Graduate_students("Riya", 78, "MCA")

print(grad_std1.name)
print(std2.name)
print(grad_std2.name)

Amit
Alice
Rohan
Riya

In [36]:
## Polymorphism

class Students(): ##  parent class
    def __init__(self, id, name, score):  ## method1
        self.id = id
        self.name = name
        self.score = score


    def std_info(self):  ## method2
        print(f" my name is {self.name} and id {self.id}  and my score is {self.score}")


std1 = Students(101, 'Alice', 78)  ## object 
##print(std1.id)
##print(std1.name)




class grad_std(Students):  ## Child class
     def __init__(self, id, name, score, course):
         super().__init__(id, name, score)
         self.course  = course

        
     def std_info(self):
         print(f" my name is {self.name} and id {self.id}  and my score is {self.score}, course is {self.course}")
        

grade_std1 = grad_std(201, 'Bob', 70, 'BCA')
grade_std2 = grad_std(202, 'Bob', 70, 'MCA')
##print(grade_std1.id)
##print(grade_std2.name)


std1.std_info()
grade_std1.std_info()

 my name is Alice and id 101  and my score is 78
 my name is Bob and id 201  and my score is 70, course is BCA

In [38]:
a = [1,2,3,4]
b = [5,6,7,8]
print(a + b)

emp = [101, 'Amit', 60]

[1, 2, 3, 4, 5, 6, 7, 8]

## Numpy in Python

In [44]:
## install numpy

In [46]:
pip install numpy

Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.2.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [47]:
import numpy as np
print(np.__version__)

2.2.5

In [48]:
## import numpy
import numpy as np

In [1]:
x = [1,2,3]
print(x, type(x))

[1, 2, 3] <class 'list'>

In [52]:
## create a array
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>

In [53]:
x = [1,2,3,4]
print(x, type(x))

[1, 2, 3, 4] <class 'list'>

In [54]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]

In [5]:
x1 = [1,2,3]
y1 = [1,2,3]
print(x1 + y1)

[1, 2, 3, 1, 2, 3]

In [7]:
import numpy as np
num1 = np.array([1,2,3])
num2 = np.array([1,2,3])
num3 = num1 + num2
print(num3)

[2 4 6]

In [21]:
## 0 nd
import numpy as np
num1 = np.array((1))
print(num1)
print(np.ndim(num1))

1
0

In [17]:
## 1 d
import numpy as np
num = np.array([1])
print(num)
print(np.ndim(num))

[1]
1

In [22]:
##  2d
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(np.ndim(a))

[[1 2 3]
 [4 5 6]]
2

In [23]:
##  2d
import numpy as np
a = np.array([[[1,2,3], [4,5,6]]])
print(a)
print(np.ndim(a))

[[[1 2 3]
  [4 5 6]]]
3

## Function in numpy

In [ ]:
##  ndim()
## shape()
## size()
## len()
## type()
## dtype()

In [24]:
## ndim()  check the dimension


import numpy as np
x1  = np.array([10,20,30])
print(x1)
print(np.ndim(x1))

[10 20 30]
1

In [28]:
## shape()   ## return rows and columns
import numpy as np
x2 = np.array([[5,8,10], [3,4,5]])
print(x2)
print(np.shape(x2))

[[ 5  8 10]
 [ 3  4  5]]
(2, 3)

In [27]:
## size()  return the number of values
import numpy as np
b1 = np.array([[10,20,30], [6,7,8]])
print(b1)
print(np.size(b1))

[[10 20 30]
 [ 6  7  8]]
6

In [32]:
## len check the length
import numpy as np
b1 = np.array([[10,20,30], [6,7,8]])
print(b1)
print(len(b1))

[[10 20 30]
 [ 6  7  8]]
2

In [34]:
import numpy as np
x1  = np.array([[10,20,30]])
print(x1)
print(len(x1))

[[10 20 30]]
1

In [35]:
## type()

import numpy as np
x1  = np.array([10,20,30])
print(x1, type(x1))

[10 20 30] <class 'numpy.ndarray'>

In [50]:
## dtype() ## check the data type
import numpy as np
x1  = np.array([10,20,30])  ## array
print(x1)
print(type(x1))
print(x1.dtype)

[10 20 30]
<class 'numpy.ndarray'>
int64

In [42]:
import numpy as np
name = np.array(['Alice', 'Bob', 'Priya'])
print(name)

['Alice' 'Bob' 'Priya']

In [43]:
print(np.dtype[name])

numpy.dtype[array(['Alice', 'Bob', 'Priya'], dtype='<U5')]

In [45]:
np.dtype[name]

numpy.dtype[array(['Alice', 'Bob', 'Priya'], dtype='<U5')]

In [51]:
import numpy as np
score = np.array([80.6, 78.7, 99.3])
print(score)

[80.6 78.7 99.3]

In [52]:
print(type(score))

<class 'numpy.ndarray'>

In [53]:
print(score.dtype)

float64

## indexing in array() - numpy

In [55]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]

In [58]:
## access the first elemnt of arr
print(arr[0])
print(arr[2])
print(arr[3])

1
3
4

In [61]:
print(arr[-1])
print(arr[-2])
print(arr[-3])

4
3
2

In [84]:
import numpy as np
num = np.array([[10,20,30],[40,50,60]])
print(num)
print(num[1])
print(num[0][1])
print(num[1][0])

print(num[1][-1])

print(num[0][0], num[1][0])

[[10 20 30]
 [40 50 60]]
[40 50 60]
20
40
60
10 40

## Slicing in array

In [ ]:
range(start:stop:step)

In [73]:
import numpy as np
arr3 = np.array([100, 150, 200, 300])
print(arr3)

[100 150 200 300]

In [74]:
## access the element from o to 3
print(arr3[:3])

[100 150 200]

In [75]:
print(arr3[1:3])

[150 200]

In [76]:
print(arr3[::-1])

[300 200 150 100]

In [77]:
print(arr3[::2])

[100 200]

In [78]:
import numpy as np
arr3 = np.array([[100, 150, 200, 300], [400, 500, 600, 700]])
print(arr3)

[[100 150 200 300]
 [400 500 600 700]]

In [80]:
print(arr3[0][1:3], arr3[1][1:3])

[150 200] [500 600]

In [81]:
print(arr3[0][::-1], arr3[1][::-1])

[300 200 150 100] [700 600 500 400]

In [82]:
print(arr3[-3:-1], arr3[-3:-1])

[[100 150 200 300]] [[100 150 200 300]]

## Operator's in numpy

In [1]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7
arr3 
arr4
## + op
print(arr1 + arr2 + arr3 + arr4)

[ 6  8 10]

In [2]:
## * op
print(arr1 * arr2)

[ 5 12 21]

In [3]:
## - op
print(arr2 - arr1)

[4 4 4]

In [6]:
## / op
x1 = np.array([4,10,8])
y1 = np.array([2,3,2])
print(x1/y1)

[2.         3.33333333 4.        ]

In [7]:
## % op
print(x1 % y1)

[0 1 0]

## Function 
## add()
## multiply()
## power()
## mod()

In [14]:
import numpy as np
a1 = np.array([10,20,30,40])
a2 = np.array([2,4,5,6])
print(np.add(a1,a2))

[12 24 35 46]

In [10]:
import numpy as np
a1 = np.array([10,20,30,40])
a2 = np.array([2,4,5,6])
print(np.multiply(a1, a2))

[ 20  80 150 240]

In [11]:
import numpy as np
a1 = np.array([10,20,30,40])
a2 = np.array([2,4,5,6])
print(np.subtract(a1,a2))

[ 8 16 25 34]

In [12]:
import numpy as np
a1 = np.array([10,20,30,40])
a2 = np.array([2,4,5,6])
print(np.power(a1,a2))

[       100     160000   24300000 4096000000]

In [13]:
import numpy as np
a1 = np.array([10,20,30,40])
a2 = np.array([2,4,5,6])
print(np.mod(a1,a2))

[0 0 0 4]

In [17]:
import numpy as np
a1 = np.array([10,20,30,40])
a2 = np.array([2,4,5,6])
print(np.sqrt(a1))
print(np.sqrt(a2))

[3.16227766 4.47213595 5.47722558 6.32455532]
[1.41421356 2.         2.23606798 2.44948974]

## Logical op

In [21]:
import numpy as np
a1 = np.array([10,12,30,40])
a2 = np.array([2,4,5,6])
a3 = (a1>10) & (a1> 15)
print(a3)

[False False  True  True]

In [22]:
import numpy as np
a1 = np.array([10,12,30,40])
a2 = np.array([2,4,5,6])
a3 = (a1>10) | (a1> 15)
print(a3)

[False  True  True  True]

## sorting in numpy

In [23]:
## asc
## desc

In [25]:
import numpy as np
a1 = np.array([10,12,3,40])
a2 = np.array([2,4,5,6])


## asc orders(sort)

print(np.sort(a1))

[ 3 10 12 40]

In [26]:
## desc order
print(np.sort(a1)[::-1])

[40 12 10  3]

In [28]:
print(a1)

[10 12  3 40]

In [29]:
print(a1[::-1])

[40  3 12 10]

## Statistical Function

In [30]:
## sum()
## max()
## min()
## mean()
## median()

In [34]:
import numpy as np
score = np.array([78,89,90,85])
print(score)

[78 89 90 85]

In [35]:
## sum()
print("Total Score:", np.sum(score))

Total Score: 342

In [36]:
## max() Check the highest score
print("Highest Score:", np.max(score))

Highest Score: 90

In [37]:
## min check the lowest score
print("Lowesr Score:", np.min(score))

Lowesr Score: 78

In [38]:
## mean() calculate the avg score
print("Avg Score:", np.mean(score))

Avg Score: 85.5

In [39]:
## median() check the median value of score
print("Median:", np.median(score))

Median: 87.0

## Filter

In [42]:
import numpy as np
a1 = np.array([10,12,30,40])
a2 = a1[a1>=15]

In [43]:
print(a2)

[30 40]

In [70]:
std_score = np.array([90, 84, 56, 78, 85])
print(std_score)

[90 84 56 78 85]

In [71]:
## filter the score where score value is more than 80
pass_std = std_score[(std_score > 80) | (std_score > 85)]

In [72]:
print(pass_std)

[90 84 85]

In [51]:
import numpy as np
num = np.array([10,13,35,40])

## check the even numbers
a2 = num[num % 2 == 0]
print(a2)

[10 40]

In [52]:
## check the odd only
a3 = num[num % 2 == 1]
print(a3)

[13 35]

## Pandas in python

In [78]:
pip install pandas

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
## What is Pandas in python?
Pandas is a powerful open-source Python library used for data manipulation, analysis, and cleaning. 
It provides easy-to-use tools to work 
with structured data—like tables from Excel, SQL databases, or CSV files.

In [79]:
import pandas as pd

In [ ]:
## Data Structures in  python
## Series
## DataFrame

In [80]:
import pandas as pd
score = pd.Series([10,20,30,40])
print(score)

0    10
1    20
2    30
3    40
dtype: int64

In [1]:
## DataFrame
import pandas as pd
students = {'Name' : ['Alice', 'Bob','David'], 'Course': ['BBA', 'MBA', 'MCA'], 'Marks': [89, 97, 85]}
##print(students)
                      
df = pd.DataFrame(students)
df

    Name Course  Marks
0  Alice    BBA     89
1    Bob    MBA     97
2  David    MCA     85

In [85]:
## Create a data of employees
import pandas as pd
employees = {'Emp_Name' : ['Amit', 'Mohan', 'Riya'], 'Salary' : [80000, 70000,60000], 'Dept_Name' : ['IT', 'HR', 'SALES']}
print(employees)

{'Emp_Name': ['Amit', 'Mohan', 'Riya'], 'Salary': [80000, 70000, 60000], 'Dept_Name': ['IT', 'HR', 'SALES']}

In [89]:
## DataFrame
emp = pd.DataFrame(employees)

In [77]:
import pandas as pd
Employees = {'Emp_id' : [101,102,103,None,105], 'Emp_Name' : ['Alice' ,'Bob', 'Mohan', 'Riya', 'Sohan'], 'Course' : ['BBA', 'MBA', 'MCA', 'BA' ,'BCA'], 'Marks' : [60,80,90,65,85]}
Employees

{'Emp_id': [101, 102, 103, None, 105],
 'Emp_Name': ['Alice', 'Bob', 'Mohan', 'Riya', 'Sohan'],
 'Course': ['BBA', 'MBA', 'MCA', 'BA', 'BCA'],
 'Marks': [60, 80, 90, 65, 85]}

In [33]:
Emp = pd.DataFrame(Employees)
Emp

   Emp_id Emp_Name Course  Marks
0   101.0    Alice    BBA     60
1   102.0      Bob    MBA     80
2   103.0    Mohan    MCA     90
3     NaN     Riya     BA     65
4   105.0    Sohan    BCA     85

In [16]:
Emp

   Emp_id Emp_Name Course
0     101    Alice    BBA
1     102      Bob    MBA
2     103    Mohan    MCA
3     104     Riya     BA
4     105    Sohan    BCA

## Function in pandas(Inspect the data)
## Shape -> Check the number of rows and columns
## size -> Return the number of elements 
## head() -> Return the top rows
## tail() -> Return the bottom rows
## info() -> Check the null and datatype
## describe() -> Calculate statistical analysis of numerical columns
## columns -> Return only column name

In [17]:
## Shape
Emp.shape

(5, 3)

In [18]:
## size
Emp.size

15

In [22]:
## head()
Emp.head(4)

   Emp_id Emp_Name Course
0     101    Alice    BBA
1     102      Bob    MBA
2     103    Mohan    MCA
3     104     Riya     BA

In [26]:
## tail()
Emp.tail(1)

   Emp_id Emp_Name Course
4     105    Sohan    BCA

In [34]:
## info()
Emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Emp_id    4 non-null      float64
 1   Emp_Name  5 non-null      object
 2   Course    5 non-null      object
 3   Marks     5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [35]:
## describe()
Emp.describe()

           Emp_id      Marks
count    4.000000   5.000000
mean   102.750000  76.000000
std      1.707825  12.942179
min    101.000000  60.000000
25%    101.750000  65.000000
50%    102.500000  80.000000
75%    103.500000  85.000000
max    105.000000  90.000000

In [36]:
## columns
Emp.columns

Index(['Emp_id', 'Emp_Name', 'Course', 'Marks'], dtype='object')

## Indexing In Pandas

In [ ]:
## loc -> Location
## iloc -> Indexing Location

In [37]:
Emp

   Emp_id Emp_Name Course  Marks
0   101.0    Alice    BBA     60
1   102.0      Bob    MBA     80
2   103.0    Mohan    MCA     90
3     NaN     Riya     BA     65
4   105.0    Sohan    BCA     85

In [38]:
## access the first row
print(Emp.loc[0])

Emp_id      101.0
Emp_Name    Alice
Course        BBA
Marks          60
Name: 0, dtype: object

In [41]:
print(Emp.loc[1])

Emp_id      102.0
Emp_Name      Bob
Course        MBA
Marks          80
Name: 1, dtype: object

In [42]:
print(Emp.loc[:3])

   Emp_id Emp_Name Course  Marks
0   101.0    Alice    BBA     60
1   102.0      Bob    MBA     80
2   103.0    Mohan    MCA     90
3     NaN     Riya     BA     65

In [43]:
print(Emp.iloc[:3])

   Emp_id Emp_Name Course  Marks
0   101.0    Alice    BBA     60
1   102.0      Bob    MBA     80
2   103.0    Mohan    MCA     90

In [44]:
print(Emp.iloc[::2])

   Emp_id Emp_Name Course  Marks
0   101.0    Alice    BBA     60
2   103.0    Mohan    MCA     90
4   105.0    Sohan    BCA     85

## Data Cleaning in pandas

In [ ]:
     Handle Missing Values
python
df.isnull().sum()             # Count missing values
df.drop(index=[0,1,2]) #3 remove rows and columns
df.drop(columns=["columnname"]) # drop the column named 44
df.drop(index=[0,1,2]) # drop rows 0,1,2 
df.drop(index=range(0,16)) # drop rows 0 to 15
 
df.dropna()                   # Remove rows with nulls
df.fillna(0)                  # Replace nulls with 0
df.fillna({'emp_name': 'Unknown', 'salary': 0})

In [68]:
import pandas as pd

# Simulated messy dataset
data = {
    'CustomerID': [101, 102, 103, 104, 104, None, None],
    'Name': ['  Alice', 'RAHUL', 'Meena', 'Rahul', 'Rahul', 'Amit', None],
    'Gender': ['f', 'M', 'F', 'm', 'M', None, None],
    'PurchaseAmount': [2500, None, 1800, 2500, 2500, 3000, None],
    'City': ['delhi', 'Delhi ', 'DELHI', 'noida', 'Noida', 'noida', None],
    'Date': ['2025-08-01', '2025/08/02', '01-08-2025', None, '2025-08-02', '2025-08-03', None]
}

Customer= pd.DataFrame(data)
Customer

   CustomerID     Name Gender  PurchaseAmount    City        Date
0       101.0    Alice      f          2500.0   delhi  2025-08-01
1       102.0    RAHUL      M             NaN  Delhi   2025/08/02
2       103.0    Meena      F          1800.0   DELHI  01-08-2025
3       104.0    Rahul      m          2500.0   noida        None
4       104.0    Rahul      M          2500.0   Noida  2025-08-02
5         NaN     Amit   None          3000.0   noida  2025-08-03
6         NaN     None   None             NaN    None        None

In [48]:
## Check the null values in columns
## isnull() -> check the null values
Customer.isnull().sum()

CustomerID        1
Name              0
Gender            1
PurchaseAmount    1
City              0
Date              1
dtype: int64

In [51]:
## drop the rows
## drop the row 1 , 3, and 4
Customer
print(Customer.drop(index=[1,3,4]))

   CustomerID     Name Gender  PurchaseAmount   City        Date
0       101.0    Alice      f          2500.0  delhi  2025-08-01
2       103.0    Meena      F          1800.0  DELHI  01-08-2025
5         NaN            None          3000.0  noida  2025-08-03

In [55]:
## Drop the rows range
Customer
print(Customer.drop(index=range(1,4)))

   CustomerID     Name Gender  PurchaseAmount   City        Date
0       101.0    Alice      f          2500.0  delhi  2025-08-01
4       104.0    Rahul      M          2500.0  Noida  2025-08-02
5         NaN            None          3000.0  noida  2025-08-03

In [60]:
## Drop the columns
## Drop te columns City and date
Customer.head(2)
print(Customer.drop(columns=['City', 'Date']))

   CustomerID     Name Gender  PurchaseAmount
0       101.0    Alice      f          2500.0
1       102.0    RAHUL      M             NaN
2       103.0    Meena      F          1800.0
3       104.0    Rahul      m          2500.0
4       104.0    Rahul      M          2500.0
5         NaN            None          3000.0

In [76]:
## dropna() -> drop the rows with  any missing values
Customer

   CustomerID     Name Gender  PurchaseAmount    City        Date
0       101.0    Alice      f          2500.0   delhi  2025-08-01
1       102.0    RAHUL      M             NaN  Delhi   2025/08/02
2       103.0    Meena      F          1800.0   DELHI  01-08-2025
3       104.0    Rahul      m          2500.0   noida        None
4       104.0    Rahul      M          2500.0   Noida  2025-08-02
5         NaN     Amit   None          3000.0   noida  2025-08-03
6         NaN     None   None             NaN    None        None

In [62]:
Customer.dropna()

   CustomerID     Name Gender  PurchaseAmount   City        Date
0       101.0    Alice      f          2500.0  delhi  2025-08-01
2       103.0    Meena      F          1800.0  DELHI  01-08-2025
4       104.0    Rahul      M          2500.0  Noida  2025-08-02

In [66]:
## Dropna -> Drop the rows with all missing values
Customer.dropna(how='all')

   CustomerID     Name Gender  PurchaseAmount    City        Date
0       101.0    Alice      f          2500.0   delhi  2025-08-01
1       102.0    RAHUL      M             NaN  Delhi   2025/08/02
2       103.0    Meena      F          1800.0   DELHI  01-08-2025
3       104.0    Rahul      m          2500.0   noida        None
4       104.0    Rahul      M          2500.0   Noida  2025-08-02
5         NaN            None          3000.0   noida  2025-08-03

In [69]:
## fillna() -> fill the null values
Customer.fillna(0)

   CustomerID     Name Gender  PurchaseAmount    City        Date
0       101.0    Alice      f          2500.0   delhi  2025-08-01
1       102.0    RAHUL      M             0.0  Delhi   2025/08/02
2       103.0    Meena      F          1800.0   DELHI  01-08-2025
3       104.0    Rahul      m          2500.0   noida           0
4       104.0    Rahul      M          2500.0   Noida  2025-08-02
5         0.0     Amit      0          3000.0   noida  2025-08-03
6         0.0        0      0             0.0       0           0

In [71]:
## 

Customer.fillna({'Name' : 'Unknown', 'City' : 'Unknown','Gender' : 'Unknown', 'PurchaseAmount' : 0, 'Date' : 'NA'})

   CustomerID     Name   Gender  PurchaseAmount     City        Date
0       101.0    Alice        f          2500.0    delhi  2025-08-01
1       102.0    RAHUL        M             0.0   Delhi   2025/08/02
2       103.0    Meena        F          1800.0    DELHI  01-08-2025
3       104.0    Rahul        m          2500.0    noida          NA
4       104.0    Rahul        M          2500.0    Noida  2025-08-02
5         NaN     Amit  Unknown          3000.0    noida  2025-08-03
6         NaN  Unknown  Unknown             0.0  Unknown          NA

In [ ]:
🧠 Common Variants
Syntax	What It Does
df.dropna(axis=0)	Drops rows with any missing value
df.dropna(how='all')	Drops rows where all values are missing
df.dropna(subset=['Name', 'Gender'])	Drops rows missing in specific columns
df.dropna(axis=1)	Drops columns with any missing value

In [75]:
Customer.dropna(subset=['CustomerID', 'Date'])

   CustomerID     Name Gender  PurchaseAmount    City        Date
0       101.0    Alice      f          2500.0   delhi  2025-08-01
1       102.0    RAHUL      M             NaN  Delhi   2025/08/02
2       103.0    Meena      F          1800.0   DELHI  01-08-2025
4       104.0    Rahul      M          2500.0   Noida  2025-08-02

In [108]:
## Drop duplicates()
## Duplicated()

## Check the duplicates
Customer.duplicated()

## drop dupliactes
Customer.drop_duplicates()

   CustomerID     Name Gender  PurchaseAmount    City        Date
0       101.0    Alice      f          2500.0   delhi  2025-08-01
1       102.0    RAHUL      M             NaN  Delhi   2025/08/02
2       103.0    Meena      F          1800.0   DELHI  01-08-2025
3       104.0    Rahul      m          2500.0   noida        None
4       104.0    Rahul      M          2500.0   Noida  2025-08-02
5         NaN     Amit   None          3000.0   noida  2025-08-03
6         NaN     None   None             NaN    None        None

## Filter in pandas

In [78]:
Employees

{'Emp_id': [101, 102, 103, None, 105],
 'Emp_Name': ['Alice', 'Bob', 'Mohan', 'Riya', 'Sohan'],
 'Course': ['BBA', 'MBA', 'MCA', 'BA', 'BCA'],
 'Marks': [60, 80, 90, 65, 85]}

In [94]:
Emp

   Emp_id Emp_Name Course  Marks
0   101.0    Alice    BBA     60
1   102.0      Bob    MBA     80
2   103.0    Mohan    MCA     90
3     NaN     Riya     BA     65
4   105.0    Sohan    BCA     85

In [81]:
## Return the EMPID
print(Emp['Emp_id'])

0    101.0
1    102.0
2    103.0
3      NaN
4    105.0
Name: Emp_id, dtype: float64

In [103]:
## retun the id and marks
Emp[['Emp_id','Emp_Name']]

   Emp_id Emp_Name
0   101.0    Alice
1   102.0      Bob
2   103.0    Mohan
3     NaN     Riya
4   105.0    Sohan